package com.causalops.api.controller;
import com.causalops.api.dto.FaultRequest; import com.causalops.api.service.*; import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.servlet.mvc.method.annotation.SseEmitter; import java.util.*;
@RestController @RequestMapping("/api") public class ApiController { final CausalOpsService app; final EventBus events; public ApiController(CausalOpsService a,EventBus e){app=a;events=e;}
 @GetMapping("/overview") Object overview(){return app.overview();} @GetMapping("/services") Object services(){return app.allServices();} @GetMapping("/services/{id}") Object service(@PathVariable String id){return app.allServices().stream().filter(x->id.equals(String.valueOf(x.get("id")))||id.equals(x.get("name"))).findFirst().orElseThrow();} @GetMapping("/topology") Object topology(){return app.topology();}
 @GetMapping("/incidents") Object incidents(){return app.incidents("");} @GetMapping("/incidents/active") Object active(){return app.incidents("where status <> 'RESOLVED'");} @GetMapping("/incidents/history") Object history(){return app.incidents("where status = 'RESOLVED'");} @GetMapping("/incidents/{id}") Object incident(@PathVariable UUID id){return app.incidents("where id='"+id+"'").stream().findFirst().orElseThrow();} @GetMapping("/incidents/{id}/root-cause") Object rca(@PathVariable UUID id){return app.rca(id);} @GetMapping("/incidents/{id}/evidence") Object evidence(@PathVariable UUID id){return app.rca(id).get("analysis");}
 @GetMapping("/predictions") Object predictions(){return app.prediction(null);}@GetMapping("/predictions/{serviceId}") Object prediction(@PathVariable String serviceId){return app.prediction(serviceId);}
 @GetMapping("/faults") Object faults(){return app.faults();}@PostMapping("/faults") @ResponseStatus(HttpStatus.CREATED) Object fault(@Valid @RequestBody FaultRequest r){return app.inject(r);}@PostMapping("/faults/{id}/stop") @ResponseStatus(HttpStatus.NO_CONTENT) void stop(@PathVariable UUID id){app.stop(id);}@PostMapping("/faults/clear") @ResponseStatus(HttpStatus.NO_CONTENT) void clear(){app.clear();}
 @PostMapping("/simulations") Object simulation(@RequestBody Map<String,Object> body){return app.simulate(body);}@GetMapping("/simulations/{id}") Object simulationGet(@PathVariable UUID id){return Map.of("id",id,"status","COMPLETED");}
 @GetMapping("/metrics") Object metrics(@RequestParam(required=false) String service){return Map.of("samples",List.of(),"service",service);}@GetMapping("/logs") Object logs(){return List.of();}@GetMapping("/traces") Object traces(){return List.of();}@GetMapping("/system/status") Object status(){return Map.of("status","UP","demoMode",true);}@GetMapping(value="/events/stream",produces=MediaType.TEXT_EVENT_STREAM_VALUE) SseEmitter stream(){return events.subscribe();}
}
