package com.causalops.api.service;
import com.causalops.api.dto.FaultRequest; import com.causalops.api.entity.ServiceEntity; import com.causalops.api.repository.ServiceRepository; import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper; import org.springframework.beans.factory.annotation.*; import org.springframework.http.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Service; import org.springframework.web.client.RestClient; import java.time.*; import java.util.*; import java.util.stream.*;
@Service public class CausalOpsService {
 private final JdbcTemplate db; private final ServiceRepository services; private final RestClient http; private final EventBus events; private final ObjectMapper json=new ObjectMapper(); @Value("${causalops.ai-url}") String aiUrl; @Value("${causalops.demo-mode}") boolean demo; @Value("${causalops.service-urls.inventory-service}") String inventoryUrl;
 public CausalOpsService(JdbcTemplate d,ServiceRepository s,RestClient h,EventBus e){db=d;services=s;http=h;events=e;}
 private Map<String,Object> service(ServiceEntity s){Map<String,Object> m=new LinkedHashMap<>();m.put("id",s.id);m.put("name",s.name);m.put("displayName",s.name);m.put("type",s.type);m.put("status",s.status);m.put("latencyP99",s.currentLatency);m.put("baselineLatency",s.baselineLatency);m.put("errorRate",s.errorRate);m.put("throughput","60 req/min");m.put("causalRole",s.status.equals("critical")?"incident_root":s.status.equals("healthy")?"unaffected":"affected");return m;}
 public List<Map<String,Object>> allServices(){return services.findAll().stream().map(this::service).toList();}
 public Map<String,Object> topology(){var edges=db.queryForList("select source_service as source,target_service as target,direction from dependencies"); return Map.of("nodes",allServices(),"edges",edges.stream().map(e->Map.of("id",e.get("source")+"-"+e.get("target"),"source",e.get("source"),"target",e.get("target"),"direction",e.get("direction"),"type","observed")).toList());}
 public Map<String,Object> overview(){var active=incidents("where status <> 'RESOLVED'");return Map.of("services",allServices(),"activeIncidents",active,"topology",topology(),"systemStatus",active.isEmpty()?"Operational":"Degraded");}
 public List<Map<String,Object>> incidents(String where){return db.queryForList("select id,incident_key as \"incidentKey\",title,severity,status,opened_at as \"openedAt\",summary,affected_services as \"affectedServices\" from incidents "+where+" order by opened_at desc");}
 public Map<String,Object> inject(FaultRequest r){ if(services.findByName(r.target()).isEmpty()) throw new NoSuchElementException("Unknown target "+r.target()); String p=write(r.parameters()==null?Map.of():r.parameters()); UUID id=UUID.randomUUID(); db.update("insert into fault_injections(id,type,target,severity,duration_seconds,parameters) values(?,?,?,?,?,cast(? as jsonb))",id,r.type(),r.target(),r.severity(),r.durationSeconds(),p); applyLiveFault(r, false); events.emit("fault.started",id,Map.of("target",r.target(),"type",r.type())); return fault(id); }
 public List<Map<String,Object>> faults(){return db.queryForList("select id,type,target,severity,duration_seconds as \"durationSeconds\",parameters,status,started_at as \"startedAt\",stopped_at as \"stoppedAt\" from fault_injections order by started_at desc");}
 public Map<String,Object> fault(UUID id){return faults().stream().filter(x->id.toString().equals(String.valueOf(x.get("id")))).findFirst().orElseThrow();}
 public void stop(UUID id){var f=fault(id);db.update("update fault_injections set status='STOPPED',stopped_at=now() where id=?",id);applyLiveFault(new FaultRequest("SERVICE_LATENCY",String.valueOf(f.get("target")),"LOW",1,Map.of("latencyMs",0)),true); events.emit("fault.stopped",id,Map.of());}
 public void clear(){db.update("update fault_injections set status='STOPPED',stopped_at=now() where status='ACTIVE'");try{http.post().uri(inventoryUrl+"/internal/fault").contentType(MediaType.APPLICATION_JSON).body(Map.of("latencyMs",0)).retrieve().toBodilessEntity();}catch(Exception ignored){} events.emit("faults.cleared","all",Map.of());}
 private void applyLiveFault(FaultRequest r, boolean stop){if(!r.type().contains("LATENCY")&&!stop)return;String url=r.target().equals("inventory-db")||r.target().equals("inventory-service")?inventoryUrl:null;if(url!=null)try{http.post().uri(url+"/internal/fault").contentType(MediaType.APPLICATION_JSON).body(Map.of("latencyMs",stop?0:r.parameters().getOrDefault("latencyMs",800))).retrieve().toBodilessEntity();}catch(Exception ignored){}}
 @Scheduled(fixedDelay=5000) public void collect(){if(!demo)return; var active=faults().stream().filter(f->"ACTIVE".equals(f.get("status"))).toList(); for(ServiceEntity s:services.findAll()){double latency=s.baselineLatency;double err=.1; for(var f:active) if(affects((String)f.get("target"),s.name)){double v=number(f.get("parameters"),"latencyMs",800); int d=distance((String)f.get("target"),s.name); if(((String)f.get("type")).contains("LATENCY"))latency+=v*Math.pow(.62,d);if("SERVICE_FAILURE".equals(f.get("type")))err+=35*Math.pow(.7,d);if("ERROR_RATE".equals(f.get("type")))err+=number(f.get("parameters"),"errorRate",20)*Math.pow(.7,d);}
  s.currentLatency=Math.round(latency);s.errorRate=Math.min(100,err);s.status=latency>s.baselineLatency*8?"critical":latency>s.baselineLatency*2?"degraded":"healthy";services.save(s); double anomaly=Math.min(1,Math.max(0,(latency/s.baselineLatency-1)/4));db.update("insert into telemetry_snapshots(service_name,p50_latency,p95_latency,p99_latency,error_rate,request_rate,db_latency,pool_utilization,anomaly_score) values(?,?,?,?,?,?,?,?,?)",s.name,latency*.6,latency*.85,latency,err,60,s.name.equals("inventory-db")?latency:null,Math.min(100,25+anomaly*70),anomaly); }
  if(!active.isEmpty()) detectAndAnalyze(); events.emit("telemetry.updated","system",allServices()); }
 private boolean affects(String root,String target){return distance(root,target)<20;} private int distance(String root,String target){if(root.equals(target))return 0;List<String> path=List.of("inventory-db","inventory-service","order-service","api-gateway");int a=path.indexOf(root),b=path.indexOf(target);return a>=0&&b>=a?b-a:20;} private double number(Object raw,String key,double fallback){try{Map<String,Object> m=json.readValue(String.valueOf(raw),new TypeReference<>(){});return ((Number)m.getOrDefault(key,fallback)).doubleValue();}catch(Exception e){return fallback;}} private String write(Object o){try{return json.writeValueAsString(o);}catch(Exception e){return "{}";}}
 private void detectAndAnalyze(){if(!incidents("where status <> 'RESOLVED'").isEmpty())return; var hot=services.findAll().stream().filter(s->s.currentLatency>s.baselineLatency*2||s.errorRate>5).toList(); if(hot.size()<2)return; UUID id=UUID.randomUUID();db.update("insert into incidents(id,incident_key,title,severity,status,summary,affected_services) values(?,?,?,?,'INVESTIGATING',?,cast(? as jsonb))",id,"INC-"+(8900+new Random().nextInt(99)),"Database Latency Cascade","HIGH","Evidence threshold exceeded across dependent services",write(hot.stream().map(s->s.name).toList()));events.emit("incident.created",id,Map.of("title","Database Latency Cascade")); analyze(id);}
 private void analyze(UUID incidentId){try {List<Map<String,Object>> telemetry=db.queryForList("select service_name as service, p99_latency as latency, error_rate as errorRate, anomaly_score as anomaly, captured_at as timestamp from telemetry_snapshots where captured_at > now()-interval '2 minutes' order by captured_at");Map body=Map.of("topology",topology(),"telemetry",telemetry);Map result=http.post().uri(aiUrl+"/analyze/root-cause").contentType(MediaType.APPLICATION_JSON).body(body).retrieve().body(Map.class);Object cand=result.get("candidates");Map root=(Map)((List)cand).get(0);UUID a=UUID.randomUUID();db.update("insert into root_cause_analyses(id,incident_id,methodology,root_cause,confidence,evidence) values(?,?,?,?,?,cast(? as jsonb))",a,incidentId,"transparent weighted graph scorer",root.get("service"),root.get("confidence"),write(result.get("evidence")));for(Object x:(List)cand){Map c=(Map)x;db.update("insert into root_cause_candidates(analysis_id,service_name,score,signals) values(?,?,?,cast(? as jsonb))",a,c.get("service"),c.get("score"),write(c.get("signals")));}db.update("update incidents set status='ROOT_CAUSE_IDENTIFIED' where id=?",incidentId); events.emit("rca.completed",incidentId,result); predict();}catch(Exception e){/* pipeline retries on next telemetry cycle */}}
 private void predict(){try {Map body=Map.of("topology",topology(),"services",allServices());List<Map> r=http.post().uri(aiUrl+"/predict/failure").contentType(MediaType.APPLICATION_JSON).body(body).retrieve().body(List.class);for(Map p:r)db.update("insert into predictions(service_name,probability,risk_level,horizon_seconds,factors) values(?,?,?,?,cast(? as jsonb))",p.get("service"),p.get("probability"),p.get("riskLevel"),p.get("horizonSeconds"),write(p.get("factors")));events.emit("predictions.updated","system",r);}catch(Exception e){}}
 public Map<String,Object> rca(UUID incident){var a=db.queryForList("select * from root_cause_analyses where incident_id=? order by completed_at desc limit 1",incident);if(a.isEmpty())throw new NoSuchElementException("RCA pending");var candidates=db.queryForList("select service_name as service,score,signals from root_cause_candidates where analysis_id=? order by score desc",a.get(0).get("id"));return Map.of("analysis",a.get(0),"candidates",candidates);}
 public Object prediction(String name){return db.queryForList("select id,service_name as service,probability,risk_level as \"riskLevel\",horizon_seconds as \"horizonSeconds\",factors,created_at as \"createdAt\" from predictions "+(name==null?"":"where service_name=? ")+" order by created_at desc",name==null?new Object[]{}:new Object[]{name});}
 public Map simulate(Map<String,Object> request){String target=String.valueOf(request.getOrDefault("target","inventory-db"));try{Map body=Map.of("topology",topology(),"services",allServices(),"target",target,"reductionPercent",request.getOrDefault("reductionPercent",70));Map r=http.post().uri(aiUrl+"/simulate/counterfactual").contentType(MediaType.APPLICATION_JSON).body(body).retrieve().body(Map.class);UUID id=UUID.randomUUID();db.update("insert into simulations(id,target,intervention,status) values(?,?,cast(? as jsonb),'COMPLETED')",id,target,write(request));for(Object x:(List)r.get("results")){Map row=(Map)x;db.update("insert into simulation_results(simulation_id,service_name,baseline,counterfactual) values(?,?,?,?)",id,row.get("service"),row.get("baseline"),row.get("counterfactual"));}r.put("id",id);events.emit("simulation.completed",id,r);return r;}catch(Exception e){throw new IllegalStateException("AI engine unavailable",e);}}
 }
